### ISSUE TITLE
Consider updating LICENSE to Apache2

### ISSUE THREAD

**Issue by tpendragon** [samvera/browse-everything#227]
The default license in the Samvera organization is APACHE2. While MIT is compatible, we may want to change it. Pinging the product owner for feedback: @mbklein

**Comment by mbklein** [comment]
Argh, I thought I had made this change ages ago. I'll get to it when I can, but I'll also happily merge a PR.

**Comment by no-reply** [comment]
The proposal is to relicense and redistribute under APACHE2.

We may or may not need to retain the MIT license in the repository. Can we look into that?

**Comment by botimer** [comment]
As I understand it, we should:

1. Apply the Apache license to the work by including its full text at the top of the LICENSE file _without_ a copyright statement.
2. Include a note that earlier versions were distributed under the MIT license (including a version number or date for courtesy), and include the full contents of LICENSE as it stands now.
3. Add a NOTICE file with an appropriate copyright statement (2018 Samvera Community) and a blurb that contributors retain copyright ownership of their contributions per one or more contributor license agreements with the Samvera Community.
4. We should check for any copyright statements in source files (unless they are fully third-party) and move them into NOTICE, in a "portions of" statement.

This comes from following the Apache Software Foundation's guidelines and the terms of both licenses.

----

_The long version..._

The above recommendation is very close to the policy of the ASF itself, because we are also not assigned copyright. They are clear that the "by reference" appendix is aimed at copyright owners.

There is an example of how to use per-file headers if we decide to do that, where the text spells out that the file is licensed to "us" by way of CLA and licensed to "you" under the ALv2, and to see the NOTICE for copyright information -- really cuts down on needless variance and churn.

### Links to sources for that info:

http://www.apache.org/dev/apply-license.html#license
http://www.apache.org/dev/apply-license.html#new
http://www.apache.org/dev/apply-license.html#contributor-copyright
http://www.apache.org/legal/src-headers.html#headers

### Rationale for including the MIT license text:

A more time-consuming alternative to including the MIT license body is to obtain consent from the contributors/copyright owners to relicense, rather than sublicense. It is not worth the effort here, given the option to include/sublicense so easily.

### A more complete picture:

The Apache license and CLAs work together. The license explicitly applies to contributions submitted for inclusion in the work unless otherwise agreed upon. The CLA qualifies as a separate agreement, explicitly noted in section 5 of the license.

The CLAs establish an inbound copyright license of contributions to the Samvera Community outside of the software license applied to the work. The software license itself governs contributions from external contributors (e.g., a small patch / typo fix from a random kind soul), and the committer (who is bound by a CLA) has the onus to determine whether the contribution is in good faith and acceptable or if it would require a signed CLA to accept. An example would be if the patch were substantial or there were any suspicion that the contributor may not have the rights to submit it. We tend to require CLAs from everyone for completeness, but it's worth noting that this is not required, provided that the ALv2 is used (because the license to use/modify the software spells out contribution terms).

The main goal is that we can distribute our software in a way that is licensed as simply and clearly as possible, making it easier for others to use or combine with other software. That starts with clarifying the terms of contribution, and pairing ALv2 with CLAs for committers does a great job of that.

I mention "Samvera Community" as an appropriate option for the copyright statement, despite not being a 501c3. An example of something similar is Chromium carrying "The Chromium Authors" in its statements since its inception. Their CLAs are almost identical to ours, meaning that Google is not assigned copyright. They chose to use a descriptive term for the collective and identify the authors for clarity. With a reference to the commit history (or an authors/contributors file), I believe this model to be simple and fully satisfactory.

### Background

1. The "Samvera Community" is established by the [MOU](https://wiki.duraspace.org/display/samvera/Samvera+Community+Framework?preview=%2F87459299%2F90979049%2FComposite_2018_MoU_and_LoA.pdf) (as the newly-named successor of the "Hydra Project").
2. The [individual](https://wiki.duraspace.org/download/attachments/87460360/Samvera%20Individual%20CLA%202017-09-20.pdf?version=1&modificationDate=1517217688994&api=v2) and [corporate](https://wiki.duraspace.org/download/attachments/87460360/Samvera%20Corporate%20CLA%202017-09-20.pdf?version=1&modificationDate=1517217689308&api=v2) CLAs signed by all committers grant to the Samvera Community "a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, sublicense, and distribute Your Contributions and such derivative works".
3. The [Apache License v2.0](http://www.apache.org/licenses/LICENSE-2.0) grants to any recipient of a licensed work "a perpetual, worldwide, non-exclusive, no-charge, royalty-free, irrevocable copyright license to reproduce, prepare Derivative Works of, publicly display, publicly perform, sublicense, and distribute the Work and such Derivative Works in Source or Object form".
4. The [MIT License](https://opensource.org/licenses/MIT) grants to "any person obtaining a copy of this software and associated documentation files (the 'Software')" permission to "deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so".
5. The MIT license explicitly grants permission to sublicense, with the requirement that the copyright statement and permission notice are retained.

**Comment by botimer** [comment]
An update on progress -- we're talking in the CCMWG about the exact steps forward here. The goal is simple consistency across projects as much as possible. We'll give another update here once clarified.

**Comment by jrgriffiniii** [comment]
There was no feedback captured from attendees on the last Samvera Tech. Call (https://wiki.duraspace.org/display/samvera/Samvera+Tech+Call+2019-05-01), and I will be soliciting for further input from a pending browse-everything maintenance meeting.

**Comment by mark-dce** [comment]
I've made the above PR to replace the MIT license with an Apache License.  I don't think there's a need to sublicense under MIT; from my perspective the original commit should have probably been Apache to begin with.   See the discussion above and rationale in the PR for additional background.

I've requested review by @mbklein to see if that makes sense to him too.
